### PR TITLE
feat: make samples/update-branch-protection.js is a flexible CLI

### PR DESCRIPTION
**Pull request by bcoe**
You can now use `add` `[rule]`, `remove` [rule]` to configure branch protection.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
This LGTM, but I wonder out loud - should we have this as a real command instead of a sample?  Like should I be able to do:

```
$ repo update-branch-protection add 'kokoro: node 12'
```

**Comment by bcoe** [comment]
@JustinBeckwith seems reasonable, perhaps create a tracking issue? a few of the samples would make sense to promote.

**Comment by alexander-fenster** [comment]
Yeah, when I wrote this sample, there was no such thing as CLI at all. :)  It really needs to be in CLI.

**Comment by JustinBeckwith** [comment]
Captured in https://github.com/googleapis/github-repo-automation/issues/304 :)

**Pull request merged**
