### PR TITLE
feat: check samples version in repo-check.js

### PR DESCRIPTION
**Pull request by alexander-fenster**
Add checking samples version to `repo-check.js` to be able to detect a situation when a package version was bumped without changing samples dependency.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
@stephenplusplus @callmehiphop can you put a quick sign off please :) I use this script to monitor repositories.

**Comment by stephenplusplus** [comment]
Docs for this would be cool 😎

**Comment by alexander-fenster** [comment]
Thanks! Added jsdoc for the new function.

**Comment by stephenplusplus** [comment]
LGTM!

**Pull request merged**
